# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
     uploads_dir: %kernel.root_dir%/../web/uploads
services:
    app.string_util:
        class: AppBundle\Utils\StringUtil

    app.twig.string_extension:
            class:     AppBundle\Twig\StringExtension
            arguments: ['@app.string_util']
            public:    false
            tags:
                - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    # ...
